### ISSUE TITLE
How to customize Tooltip Title (ChoroplethDataLayer with GeoJSON)

### ISSUE THREAD

**Issue by cdrfun** [humangeo/leaflet-dvf#110]
Hi there,
I have a GeoJSON dataset and use the following data layer definition:
```
var dataLayer = new L.ChoroplethDataLayer(data, {
	recordsLayer: 'features',
	locationMode: L.LocationModes.GEOJSON,
	maxZoom: 18,
	displayOptions: {
		'properties.NAME_3' : {
			displayName: 'Landkreis'
		}
	},	
	layerOptions: {
		gradient: true,
		fillOpacity: 0.8,
		weight: 1.0,
		opacity: 1.0,
		color: '#000000'
	},
	tooltipOptions: {
		iconSize: new L.Point(100, 80),
		iconAnchor: new L.Point(-10, 0)
	}
});
```
This results in:
![image](https://cloud.githubusercontent.com/assets/146877/25898446/7b90d28a-358c-11e7-93da-f9ebfea85da3.png)

But I want to write the Information in properties.NAME_3 (Landkreis) in the title of the tooltip where it currently says [object Object].

How can I achieve that? Many thanks in advance!

**Comment by sfairgrieve** [comment]
Use the `locationTextField` option.  This can either be a reference to a property like `properties.NAME_3` or it can be a function that takes a record as input and returns a string.  Try this:

```javascript
var dataLayer = new L.ChoroplethDataLayer(data, {
	recordsLayer: 'features',
	locationMode: L.LocationModes.GEOJSON,
        locationTextField: 'properties.NAME_3',
	maxZoom: 18,
	displayOptions: {
		'properties.NAME_3' : {
			displayName: 'Landkreis'
		}
	},	
	layerOptions: {
		gradient: true,
		fillOpacity: 0.8,
		weight: 1.0,
		opacity: 1.0,
		color: '#000000'
	},
	tooltipOptions: {
		iconSize: new L.Point(100, 80),
		iconAnchor: new L.Point(-10, 0)
	}
});
```

**Comment by cdrfun** [comment]
Thank you! Works like a charm 😃
