### ISSUE TITLE
FlowLine, CustomColorFunction & min

### ISSUE THREAD

**Issue by jack-r-abbit** [humangeo/leaflet-dvf#54]
I created a CustomColorFunction and gave it min/max values and small set of colors (red, yellow, green). When used with a data set that contains values BELOW the min, those low values get assigned the color from the max end of the scale, not the min. I expected the numbers below the min would get the min end of the scale.

To illustrate, I've made this jsFiddle: http://jsfiddle.net/wzfp1mLh/1/
Notice my color function has a min of 35 and a max of 60. Notice the data starts out above 60 and gradually steps down to 34 and then back up 35. I expected the tail end of this FlowLine to be all red but the point that is 34 is green.

I'm not sure if this is "just the way it is" or a bug in one of those components.

**Comment by sfairgrieve** [comment]
Thanks for pointing this out.  Let me look into this.  You're understanding of how it should work sounds correct to me.

**Comment by sfairgrieve** [comment]
I see the problem.  I'll push a fix soon.

**Comment by sfairgrieve** [comment]
Just pushed a fix to master.  Let me know if this fixes your issue.

**Comment by jack-r-abbit** [comment]
That fixed the problem. Great plugin you have here. Thank you!
