### ISSUE TITLE
Leafet-dvf markers not showing correctly

### ISSUE THREAD

**Issue by birdage** [humangeo/leaflet-dvf#60]
ive been following the [markers example](https://github.com/humangeo/leaflet-dvf/blob/master/examples/html/markers.html) and i get a marker but it look nothing like what the examples page looks like, any ideas? just looks like a polygon, without any of the styling? css missing somewhere?

![screen shot 2015-04-10 at 3 08 21 pm](https://cloud.githubusercontent.com/assets/547228/7094900/a288a51c-df93-11e4-9761-f71ab944e892.png)

**Comment by sfairgrieve** [comment]
Can you provide some more details about your setup/how you installed it and if there are any errors in the Chrome/Firefox debug console?  Not sure why it wouldn't be working, unless paths are off or CSS is missing as you mentioned.

**Comment by birdage** [comment]
i think your right, there might be something up with my css as i can get it to work in a standalone example. ill close this for now unless i cant fix it :smile:

**Comment by birdage** [comment]
it was a css issue im all good now!
