### ISSUE TITLE
IE9+ error with gradient option on L.MapMarker

### ISSUE THREAD

**Issue by iktl** [humangeo/leaflet-dvf#68]
I'm getting errors in IE9+ when trying to use `L.MapMarker` with a gradient option. It's throwing an error at:

https://github.com/humangeo/leaflet-dvf/blob/1.0dev/src/leaflet.dvf.markers.js#L397

citing: `Unable to get property 'length' of undefined or null reference`. Viewing the online markers example produces the same results. Has anyone seen the same?

**Comment by sfairgrieve** [comment]
@iktl I haven't seen this, but I'll do some testing in IE9+.  I recently updated this file (w/in the past day or so) to change the line preceding this error from:
```
var children = gradient.children;
``` 
to:
```
var children = gradient.childNodes;
```
Due to some errors in Safari - Safari didn't support the children property, and I'm assuming neither does IE.  Can you check and make sure you're definitely using the latest code?

**Comment by iktl** [comment]
The chunk I'm running is:
```
        var children = gradient.childNodes;
        var childLength = children.length;
```
I'll try and run an older version and see if that changes, otherwise I'll sit tight and see the results of your testing.

**Comment by iktl** [comment]
I'll look into IE and childNodes some, because I'm seeing some documented errors out there and see what I can dig up. If I can find a solution I'll post it here.

**Comment by sfairgrieve** [comment]
I pushed up a change that will hopefully fix this.  I haven't had a chance to test in IE 9 yet, so let me know the latest code doesn't fix it.

**Comment by iktl** [comment]
No joy – using https://github.com/humangeo/leaflet-dvf/blob/1.0dev/dist/leaflet-dvf.markers.js, I'm now getting an undefined error for `Evented` during the `L.Evented.extend()` call.

**Comment by sfairgrieve** [comment]
I'll look into this some more, but it sounds like the childNodes/children code is no longer the issue.  On which line is the error occurring?

**Comment by sfairgrieve** [comment]
So the only reference to L.Evented is in leaflet-dvf.utils.js in the L.Animation class (line 1293).  I don't believe I'm actually using that class for anything within the framework at the moment, so if you're comfortable with rebuilding the code using grunt, you could remove that code from leaflet-dvf.utils.js and then rebuild and see if that fixes things.  The strange thing is that L.PosAnimation within the Leaflet code calls L.Evented.extend(), so it's weird that that's not throwing an error as well.

**Comment by sfairgrieve** [comment]
I'm also downloading a VM with IE 9 on it, so I should be able to try out some fixes soon.

**Comment by sfairgrieve** [comment]
I'm not seeing these issues on my IE 9 VM.  I do see issues with the L.SVGMarker class that I'll fix.  Is this occurring in a particular example or in custom code?  If it's custom code, do you mind sharing your script imports or some sample HTML/JS that's similar to what your doing?

**Comment by iktl** [comment]
I'd say go ahead and close this for now. Whatever recent changes you pushed have fixed the IE issues in the dist/examples pages in the 1.0dev branch. I'm still getting an error in my application code but I'd say this new issue is probably an interaction with something else in my codebase. I'll poke around and see what I can work out, but it's not coming from leaflet-dvf anymore.

**Comment by iktl** [comment]
Alright, figured it out. I had to switch over to using Leaflet 1.0 (I think this is mentioned somewhere around the 1.0 dev branch of leaflet-lvf, so my bad) instead of mapbox.js (which is based off the last stable release of leaflet). I have to update some code on my end to use the Leaflet library itself and not the Mapbox superset, but that's no problem. This has fixed the actual leaflet-lvf errors I was getting. Thanks for helping troubleshoot this.
