### ISSUE TITLE
WeightedPolyline Opacity Changes

### ISSUE THREAD

**Issue by 11samype** [humangeo/leaflet-dvf#69]
I am using a weighted polyline for a project and have them inside of a layer group that is turned on and off by the user. I have found that when removing and then adding the layer back to the map, the opacity of the weighted polyline increases each time the layer is added back. Is this a known issue?

**Comment by sfairgrieve** [comment]
This sounds like a new issue.  I'll look into it and hopefully have a fix soon.  Is this the 0.7.3 version (master branch) or the 1.0dev branch or both?

**Comment by 11samype** [comment]
The master branch, specifically the 0.2.4 release. I haven't tried it with 1.0dev.

Here is a fiddle I made to show it: https://jsfiddle.net/wSytj/92/

click the map to remove and then add

**Comment by sfairgrieve** [comment]
Just pushed a fix.  Let me know if this works for you.

**Comment by 11samype** [comment]
Works great!
