### ISSUE TITLE
includeLayer options for Leaflet DVF Chloropleth not working for numeric data ranges

### ISSUE THREAD

**Issue by anatamambo** [humangeo/leaflet-dvf#76]
I am having problem with implementing the Leaflet DVF includeLayer function (Equivalent to filter) as follows for a Chloropleth GeoJSON Data Layer:

includeLayer: function(feature) {
return (feature.Total_Population <= 1000) && (feature.Total_Population >= 500);
}

Unfortunately there isn't much documentation online. From what i've read, it seems that this can only be applied on string type data and not on numbers. Is this so? Or am I missing something? Thanks in advance for any assistance regarding this issue!

**Comment by sfairgrieve** [comment]
That should definitely work.  Is `feature` in this case a GeoJSON feature?  If that's true, then it should probably be:

```javascript
includeLayer: function(feature) {
     return (feature.properties.Total_Population <= 1000) && (feature.properties.Total_Population >= 500);
}
```

What happens if you open the Chrome or Firefox dev tools and put a breakpoint on the return line?  What does `feature.Total_Population` look like?

**Comment by anatamambo** [comment]
Darn missed the properties part ... It fixed up my coding, thank you so much Scott!
