### ISSUE TITLE
Unable to Remove Chloropleth Layer from Map

### ISSUE THREAD

**Issue by anatamambo** [humangeo/leaflet-dvf#77]
Thanks for the help on the previous issue, another issue is regarding removing layers from the map ... I load the GeoJSON dataset (Triggered by a button) as follows:

     function addAreaData()
     {
     var data = $.getJSON("data/area.geojson");

    data.then(function(data) {
          var area = new L.ChoroplethDataLayer(data, {
          //Options in here

         map.addLayer(area);
         });
  }

Now if I try to trigger a remove layer event with a button to remove it using: 

map.removeLayer(area);

Nothing happens and the data remains in the map. Am I doing something wrong here?

**Comment by sfairgrieve** [comment]
Without looking at your code, it's hard to say.  `map.removeLayer(area);` should work.  The only things I can think of are the click handler for the button isn't firing for some reason, or `area` is not defined when the click handler code is executed.  If `area` is defined in your `then` block, does the click handler get defined after that, also in the `then` block?  I guess what I'm getting at is this, is `area` scoped such that both `addAreaData` and `removeAreaData` have access to it?

**Comment by anatamambo** [comment]
Area is defined globally as follows:

 var area = L.geoJson(null, null); 

There are 2 click handlers, 1 to 'Add Data' which executes the aforementioned function 'addAreaData()' which works just fine and a 'Remove Data' button which removes the data in a separate function.

**Comment by sfairgrieve** [comment]
I'm not sure what the issue might be, then.  I'll throw together an example that matches what I think you're saying and share it with you if it works.

**Comment by anatamambo** [comment]
OK thanks for that Scott!

**Comment by sfairgrieve** [comment]
@anatamambo checkout the choropleth example here: https://github.com/humangeo/leaflet-dvf/blob/master/examples/html/choropleth.html.  This is similar to your use case - hope it helps.  Sorry for the delay, btw.  Without seeing your code other than the example you posted above, I'm thinking that b/c `addAreaData` requests the JSON everytime it's just adding a new layer each time the data is returned, and `removeAreaData` is removing the last added layer, not all the layers.  Just a guess that could be way off.

**Comment by anatamambo** [comment]
Nice! Thanks so much for your help ... It's working liek clockwork on my end ... Thank you so much Scott!
