### ISSUE TITLE
Lost the ability to override dynamic options in DataLayer

### ISSUE THREAD

**Issue by rickj33** [humangeo/leaflet-dvf#81]
Before, I could define a DataLayer with these options
 leafletLayer = new L.DataLayer({}, {
                pane               : 'markerPane',
                recordsField       : null,
                latitudeField      : 'lat',
                longitudeField     : 'long',
                locationMode       : L.LocationModes.LATLNG,
                getMarker          : this.getMarker,
                dynamicOptions     : this._getToolTipOptions
}

And the DataLayer would call the function I had passed for the dynamicOptions.

However, In the 1.0dev branch, this is no longer the case.
I traced the issue down to the function recordToLayer 
on the line 
             var dynamicOptions = this._getDynamicOptions(record);

before it was 
  var dynamicOptions = this.options.dynamicOptions ? this.options.dynamicOptions(record) : this._getDynamicOptions(record);

Was there a reason behind this change? and if so, how should i override the data which gets displayed on the mouse hover event?

Thanks
Rick

**Comment by sfairgrieve** [comment]
Thanks for pointing this out.  I think this must have been an oversight on my part.  It's sometimes difficult to keep updates synced in both places.  I'll make sure the same functionality gets added to the 1.0dev branch.

**Comment by sfairgrieve** [comment]
@rickj33 This should now be fixed.  Let me know if you run into any other issues.

**Comment by rickj33** [comment]
Thanks for addressing this so fast.
Rick
