### ISSUE TITLE
Question: When generating a numeric legend

### ISSUE THREAD

**Issue by rickj33** [humangeo/leaflet-dvf#86]
I am implementing a custom legend to produce this
![image](https://cloud.githubusercontent.com/assets/154450/12631669/47570150-c518-11e5-95a0-a069b446ec8b.png)

I have it working, but when going through the code in L.Datalayer _getLegend  I saw this line of code 
```javascript
var weight = layerOptions.weight || 0;
//then later used when breaks are defined 
   segmentWidths.push(width - lastWidth - 2 * weight);
````
the question is, what is the -2 * weight mean, is it compensating for the size of the border? and if so does weight mean border width?

**Comment by sfairgrieve** [comment]
That's correct.  The code is trying to fit n cells with left and right borders into a particular width. The legend sets the border width based on the weight style property, which is the Leaflet way of setting SVG shape/path stroke width.

**Comment by rickj33** [comment]
thanks for the explanation
