### ISSUE TITLE
Utilizing custom panes

### ISSUE THREAD

**Issue by csxphil** [humangeo/leaflet-dvf#92]
Is there support for using panes in the 1.0dev branch with Chart Layers?
 Specifying it in options like this:
`{ pane:'fore', layerOptions: {...},chartOptions:{...}}`

**Comment by sfairgrieve** [comment]
This should work if you stick the _pane_ option under _layerOptions_ like so:

```javascript
{
     layerOptions: {
          pane: 'fore'
     }
}
```

**Comment by csxphil** [comment]
Shucks, that worked! Thank you!
